# Generated by Django 4.0.6 on 2023-08-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('appetizers', 'appetizers'), ('main courses', 'main courses'), ('desserts', 'desserts'), ('Breakfast', 'Breakfast')], max_length=50),
        ),
    ]
