# Generated by Django 4.0.6 on 2023-09-02 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_recipe_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
