# Generated by Django 4.0.6 on 2023-09-02 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_delete_userprofile'),
    ]

    operations = [

    ]
