# Generated by Django 4.0.6 on 2023-09-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('Appetizers', 'Appetizers'), ('Main', 'Main'), ('Desserts', 'Desserts'), ('Drinks', 'Drinks'), ('Breakfast', 'Breakfast')], max_length=30),
        ),
    ]
